- name: install python2 on CentOS or Ubuntu instances
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      raw: test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal) || (yum -y install python libselinux-python)
      when: check_python.rc != 0

- name: misc task on instance
  hosts: "*"
  tasks:
    - debug: var=ansible_host
